# Generated by Django 3.0.7 on 2020-07-02 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('business_name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('complement', models.CharField(blank=True, max_length=60, null=True)),
                ('neighborhood', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('zip_code', models.CharField(blank=True, max_length=8)),
                ('phones', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name_owner', models.CharField(blank=True, max_length=60)),
                ('last_name_owner', models.CharField(blank=True, max_length=60)),
                ('cpf_owner', models.CharField(blank=True, max_length=11)),
                ('email_owner', models.EmailField(blank=True, max_length=254)),
                ('id_owner', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
